name: gedankenfolger/text-media
typeName: gedankenfolger_textmedia
group: default
prefixFields: true
prefixType: vendor
fields:
  - identifier: Gedankenfolger/Header
    type: Basic
  -
    identifier: bodytext
    useExistingField: true
    enableRichtext: true
    richtextConfiguration: full
  -
    identifier: tab_media
    type: Tab
    label: Media
  -
    identifier: Gedankenfolger/Assets
    type: Basic
  -
    identifier: appearance_tab
    type: Tab
    label: LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:tabs.appearance
  -
    identifier: frames_palette
    type: Palette
    label: LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:palette.frames
    fields:
      -
        identifier: layout
        useExistingField: true
      -
        identifier: frame_class
        useExistingField: true
      -
        identifier: space_before_class
        useExistingField: true
      -
        identifier: space_after_class
        useExistingField: true
      -
        type: Linebreak
      -
        identifier: grid
        label: Grid
        type: Select
        renderType: selectSingle
        displayCond:
          OR:
            - 'FIELD:imageorient:=:25'
            - 'FIELD:imageorient:=:26'
        items:
          - label: '16 / 8'
            value: '16_8'
          - label: '15 / 9'
            value: '15_9'
          - label: '14 / 10'
            value: '14_10'
          - label: '13 / 11'
            value: '13_11'
          - label: '12 / 12'
            value: '12_12'
          - label: '11 / 13'
            value: '11_13'
          - label: '10 / 14'
            value: '10_14'
          - label: '9 / 15'
            value: '9_15'
          - label: '8 / 16'
            value: '8_16'